baseURL = "https://aoken7.github.io/"
title = "incomplete"
theme = "erblog"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Aoken"
    badge = "orange"
    quote = "red"
    #notice = "Hello, world. This is a notification."
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    logo = "/images/icon.png"
    portrait = "/images/avater.jpeg"
    bio = """
    <ul>
        <li>・B3</li>
        <li>・大阪工業大学情報科学部</li>
        <li>・自然言語処理研</li>
        <li>・AtCoder茶色</li>
        <li>・応用情報技術者</li>
    </ul>
    
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


#[[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

#[[menu.footer]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
#series = "series"

[[menu.icon]]
    url = "https://twitter.com/_aoken"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/aoken7/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://atcoder.jp/users/aoken_7"
    name = "link"
    weight = 3

[[menu.icon]]
    url = "https://www.amazon.jp/hz/wishlist/ls/H3GA3NYGLU87?ref_=wl_share"
    name = "amazon"
    weight = 4