baseURL = "https://example.com"
title = "Hoge Site"
theme = "erblog"
paginate = 3
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Aoken"
    badge = "orange"
    quote = "red"
    #notice = "Hello, world. This is a notification."
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    # logo = "//blog.ertuil.top/avater.png"
    portrait = "/images/avater.jpeg"
    bio = """
    <p> Hoge hoge hoge. </p>
    """
    # copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "https://twitter.com/_aoken"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/aoken7/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://atcoder.jp/users/aoken_7"
    name = "link"
    weight = 3

[[menu.icon]]
    url = "https://www.amazon.jp/hz/wishlist/ls/H3GA3NYGLU87?ref_=wl_share"
    name = "amazon"
    weight = 4